### PR TITLE
Implementation: create a page that displays rocket information

### PR DESCRIPTION
**Pull request by gagandeepp**
# Linked Issue
https://github.com/stepzen-samples/stepzen-spacex-graphql/issues/7
https://github.com/stepzen-samples/stepzen-spacex-graphql/issues/8
# Description
It will add a link on homepage to display the rocket information link
# Methodology
React Router added to facilitate the page navigation and a new component added to display the rocket information 

image

image

### CODE REVIEW

**Comment by gagandeepp** [comment]
@Cerchie here you go

**Comment by Cerchie** [comment]
> @Cerchie here you go

thanks! Am working on looking at the additions locally.

**Comment by Cerchie** [comment]
> Once you add the hacktoberfest-accepted label . This PR will contribute to my hacktoberfest- profile

yes -- it should anyway once I merge since it has the hacktoberfest label and topc but I can do that if you like.

one more change-- can you add react-router-dom to the package.json?

**Comment by gagandeepp** [comment]
> > Once you add the hacktoberfest-accepted label . This PR will contribute to my hacktoberfest- profile
> 
> yes -- it should anyway once I merge since it has the hacktoberfest label and topc but I can do that if you like.
> 
> one more change-- can you add react-router-dom to the package.json?

It is already their in the PR

**Comment by Cerchie** [comment]
@gagandeepp  StepZen'd love to send you stickers to thank you for your contribution-- you can send us your address through this page https://stepzen.com/stickers

**Comment by gagandeepp** [comment]
> @gagandeepp StepZen'd love to send you stickers to thank you for your contribution-- you can send us your address through this page https://stepzen.com/stickers

Location is undeliverable as per your api as I am based in india

**Pull request merged**
